% 1. Connessione (Creazione del file da zero nella cartella database)
if ~exist('database', 'dir')
    mkdir('database');
end
conn = sqlite('database/sistema_sanitario.db');

% 2. Creazione Tabella MALATTIE
execute(conn, ['CREATE TABLE IF NOT EXISTS Malattie (' ...
    'ID_Malattia INTEGER PRIMARY KEY AUTOINCREMENT, ' ...
    'Nome TEXT UNIQUE, ' ...
    'Descrizione TEXT, ' ...
    'Percentuale_Donne REAL, ' ...
    'Percentuale_Uomini REAL)']);

% 3. Creazione Tabella DATI EPIDEMIOLOGICI
execute(conn, ['CREATE TABLE IF NOT EXISTS Dati_Epidemiologici (' ...
    'ID_Dato INTEGER PRIMARY KEY AUTOINCREMENT, ' ...
    'Nome_Malattia TEXT, ' ...
    'Anno INTEGER, ' ...
    'Regione TEXT, ' ...
    'Casi_Totali INTEGER, ' ...
    'Sintomatici INTEGER, ' ...
    'Gravita_Media REAL, ' ...
    'Tasso_Mortalita REAL, ' ...
    'Tot_Nazionale_Percentuale REAL)']);

% 4. Creazione Tabella UTENTI
execute(conn, ['CREATE TABLE IF NOT EXISTS Utenti (' ...
    'ID_Utente INTEGER PRIMARY KEY AUTOINCREMENT, ' ...
    'Username TEXT UNIQUE, ' ...
    'Password TEXT, ' ...
    'Ruolo TEXT)']);

% 5. Inserimento Utenti di Prova
try
    execute(conn, "INSERT INTO Utenti (Username, Password, Ruolo) VALUES ('guest', 'guest123', 'Guest')");
    execute(conn, "INSERT INTO Utenti (Username, Password, Ruolo) VALUES ('ricercatore', 'admin123', 'Ricercatore')");
catch
end

% 6. Inserimento di esempio (Le tue "righe")
try
    execute(conn, "INSERT INTO Malattie (Nome, Descrizione, Percentuale_Donne, Percentuale_Uomini) VALUES ('Malattia Esempio 1', 'Descrizione test', 50.0, 50.0)");
catch
end

% 7. Messaggio finale e chiusura
disp('Database ricreato da zero, tabelle pronte e righe inserite!');
close(conn);