function dashboard_clinica_anagrafica()
    figClinica = figure('Name', 'Anagrafica Clinica Patologie', 'NumberTitle', 'off', ...
        'MenuBar', 'none', 'ToolBar', 'none', 'Position', [400, 150, 600, 450], 'Color', 'w');

    uicontrol('Parent', figClinica, 'Style', 'text', ...
        'String', 'CENTRO CONSULTAZIONE SCHEDE ANAGRAFICHE', ...
        'Position', [20, 395, 560, 35], 'FontSize', 13, 'FontWeight', 'bold', ...
        'BackgroundColor', 'w', 'ForegroundColor', [0.00 0.45 1.00]);

    uipanel('Parent', figClinica, 'Title', 'Fase 1: Configurazione Patologia Target', ...
        'Position', [0.05, 0.65, 0.90, 0.20], 'BackgroundColor', 'w', ...
        'FontWeight', 'bold', 'ForegroundColor', [0.2 0.2 0.2]);

    
    uicontrol('Parent', figClinica, 'Style', 'text', ...
        'String', 'Seleziona Malattia dal Database Relazionale:', 'Position', [50, 312, 300, 20], ...
        'FontSize', 10, 'BackgroundColor', 'w', 'ForegroundColor', [0 0 0], 'HorizontalAlignment', 'left');

    menuM = uicontrol('Parent', figClinica, 'Style', 'popupmenu', ...
        'String', {'-- Seleziona Patologia --', 'Sclerosi Multipla', 'Celiachia', 'Diabete Tipo 1', 'Tiroidite di Hashimoto', 'Morbo di Crohn'}, ...
        'Position', [340, 312, 210, 25], 'FontSize', 10, 'BackgroundColor', 'w', 'ForegroundColor', [0 0 0]);

    uipanel('Parent', figClinica, 'Title', 'Fase 2: Estrazione Moduli Clinici Informativi', ...
        'Position', [0.05, 0.08, 0.90, 0.52], 'BackgroundColor', 'w', ...
        'FontWeight', 'bold', 'ForegroundColor', [0.2 0.2 0.2]);

    
    uicontrol('Parent', figClinica, 'Style', 'pushbutton', 'String', ' DESCRIZIONE CLINICA', ...
        'Position', [60, 160, 220, 45], 'BackgroundColor', [0.20 0.60 1.00], 'ForegroundColor', 'w', 'FontWeight', 'bold', ...
        'Callback', @(~,~) controllaEInvia(menuM, 1));

    uicontrol('Parent', figClinica, 'Style', 'pushbutton', 'String', 'QUADRO SINTOMATOLOGICO', ...
        'Position', [320, 160, 220, 45], 'BackgroundColor', [1.00, 0.35, 0.10], 'ForegroundColor', 'w', 'FontWeight', 'bold', ...
        'Callback', @(~,~) controllaEInvia(menuM, 2));

    uicontrol('Parent', figClinica, 'Style', 'pushbutton', 'String', ' ORGANI COINVOLTI (MAPPA)', ...
        'Position', [60, 75, 220, 45], 'BackgroundColor', [0.60, 0.40, 0.80], 'ForegroundColor', 'w', 'FontWeight', 'bold', ...
        'Callback', @(~,~) controllaEInvia(menuM, 3));

    uicontrol('Parent', figClinica, 'Style', 'pushbutton', 'String', ' PROTOCOLLI TERAPEUTICI', ...
        'Position', [320, 75, 220, 45], 'BackgroundColor', [0.10, 0.70, 0.40], 'ForegroundColor', 'w', 'FontWeight', 'bold', ...
        'Callback', @(~,~) controllaEInvia(menuM, 4));
end

function controllaEInvia(menuM, tipoScript)
    idx = menuM.Value;
    if idx == 1
        errordlg('Devi prima selezionare una patologia valida dal menu a tendina!', 'Attenzione');
        return;
    end
    
    idMalattia = idx - 1; 
    
    switch tipoScript
        case 1, scheda_descrizione(idMalattia);
        case 2, scheda_sintomi(idMalattia);
        case 3, scheda_organi(idMalattia);
        case 4, scheda_terapie(idMalattia);
    end
end