% INTERFACCIA PRINCIPALE: LOGIN, CENTRO CONTROLLO ED ESPORTAZIONE DATI 
function login_centro_controllo()
    clear; clc; close all;

   
    % SCHERMATA GRAFICA DI LOGIN
  
    figLogin = figure('Name', 'Accesso Sistema', 'NumberTitle', 'off', ...
        'MenuBar', 'none', 'ToolBar', 'none', ...
        'Position', [500, 300, 420, 340], 'Color', 'w');

    uicontrol('Parent', figLogin, 'Style', 'text', ...
        'String', 'SISTEMA EPIDEMIOLOGICO ITALIA', ...
        'Position', [20, 265, 380, 30], 'FontSize', 14, ...
        'FontWeight', 'bold', 'BackgroundColor', 'w', ...
        'ForegroundColor', [0.00 0.45 1.00]);

    uicontrol('Parent', figLogin, 'Style', 'text', ...
        'String', 'Seleziona il tuo Profilo:', ...
        'Position', [50, 205, 320, 20], ...
        'FontSize', 10, 'FontWeight', 'bold', ...
        'BackgroundColor', 'w', 'HorizontalAlignment', 'left', ...
        'ForegroundColor', [0.2 0.2 0.2]);

    menuRuolo = uicontrol('Parent', figLogin, 'Style', 'popupmenu', ...
        'String', {'Guest (Ospite)', 'Ricercatore Clinico'}, ...
        'Position', [50, 175, 320, 25], 'FontSize', 10);

    txtPassword = uicontrol('Parent', figLogin, 'Style', 'text', ...
        'String', 'Codice Identificativo Ricercatore:', ...
        'Position', [50, 135, 320, 20], ...
        'FontSize', 10, 'FontWeight', 'bold', ...
        'BackgroundColor', 'w', 'ForegroundColor', [0.2 0.2 0.2], ...
        'HorizontalAlignment', 'left');

    editPassword = uicontrol('Parent', figLogin, 'Style', 'edit', ...
        'String', '', 'Position', [50, 110, 320, 25], ...
        'FontSize', 11, ...
        'Enable', 'off', ...
        'BackgroundColor', [0.9 0.9 0.9]);

    set(menuRuolo, 'Callback', @(src,~) gestisciCampi(src, txtPassword, editPassword));

    uicontrol('Parent', figLogin, 'Style', 'pushbutton', ...
        'String', 'ACCEDI AL SISTEMA', ...
        'Position', [80, 35, 260, 42], ...
        'FontSize', 11, 'FontWeight', 'bold', ...
        'BackgroundColor', [0.00 0.45 1.00], 'ForegroundColor', 'w', ...
        'Callback', @(~,~) verificareLogin(menuRuolo, editPassword, figLogin));
end

%  LOGIN CONTROL

function gestisciCampi(src, txt, editField)
    if src.Value == 2
        set(txt, 'Enable', 'on');
        set(editField, 'Enable', 'on');
        set(editField, 'BackgroundColor', 'white');
    else
        set(txt, 'Enable', 'off');
        set(editField, 'Enable', 'off');
        set(editField, 'String', '');
        set(editField, 'BackgroundColor', [0.9 0.9 0.9]);
    end
end

function verificareLogin(menuRuolo, editPassword, figLogin)
    if menuRuolo.Value == 2
        if strcmp(get(editPassword, 'String'), 'ricercatore123')
            close(figLogin);
            apriCentroControllo("Ricercatore");
        else
            errordlg('Codice Ricercatore Errato!', 'Errore');
        end
    else
        close(figLogin);
        apriCentroControllo("Guest");
    end
end


%  CENTRO CONTROLLO

function apriCentroControllo(ruolo)

    figCentro = figure('Name', ['Centro Controllo - ' char(ruolo)], ...
        'NumberTitle', 'off', 'MenuBar', 'none', ...
        'ToolBar', 'none', 'Position', [350, 80, 680, 600], 'Color', 'w');

    uicontrol('Parent', figCentro, 'Style', 'text', ...
        'String', ['PANNELLO: ' upper(char(ruolo))], ...
        'Position', [30, 545, 620, 30], ...
        'FontSize', 14, 'FontWeight', 'bold', ...
        'BackgroundColor', 'w', 'ForegroundColor', [0.00 0.45 1.00]);

    % GUEST BUTTONS
    uicontrol('Parent', figCentro, 'Style', 'pushbutton', ...
        'String', 'MAPPA EPIDEMIOLOGICA', ...
        'Position', [40, 445, 280, 42], ...
        'BackgroundColor', [0.00 0.75 0.20], 'ForegroundColor', 'w', ...
        'Callback', @(~,~) evalin('base', 'mappa_epidemiologica'));

    uicontrol('Parent', figCentro, 'Style', 'pushbutton', ...
        'String', 'COSTI SANITARI', ...
        'Position', [350, 445, 290, 42], ...
        'BackgroundColor', [0.95 0.65 0.00], 'ForegroundColor', 'w', ...
        'Callback', @(~,~) evalin('base', 'grafico_costi'));

    uicontrol('Parent', figCentro, 'Style', 'pushbutton', ...
        'String', 'ETA', ...
        'Position', [40, 385, 280, 42], ...
        'BackgroundColor', [0.90 0.00 0.60], 'ForegroundColor', 'w', ...
        'Callback', @(~,~) evalin('base', 'grafico_eta'));

    uicontrol('Parent', figCentro, 'Style', 'pushbutton', ...
        'String', 'SESSO', ...
        'Position', [350, 385, 290, 42], ...
        'BackgroundColor', [0.50 0.00 0.90], 'ForegroundColor', 'w', ...
        'Callback', @(~,~) evalin('base', 'grafico_sesso'));

    % RICERCATORE
    if ruolo == "Ricercatore"

        uicontrol('Parent', figCentro, 'Style', 'pushbutton', ...
            'String', 'CONFRONTO MALATTIE', ...
            'Position', [40, 260, 590, 42], ...
            'BackgroundColor', [0.00 0.65 0.68], 'ForegroundColor', 'w', ...
            'Callback', @(~,~) evalin('base', 'grafico_confronto'));

        uicontrol('Parent', figCentro, 'Style', 'pushbutton', ...
            'String', 'PREVISIONI', ...
            'Position', [40, 200, 590, 42], ...
            'BackgroundColor', [0.08 0.18 0.36], 'ForegroundColor', 'w', ...
            'Callback', @(~,~) evalin('base', 'grafico_previsione'));

        uicontrol('Parent', figCentro, 'Style', 'pushbutton', ...
            'String', 'EXPORT EXCEL', ...
            'Position', [40, 95, 280, 40], ...
            'BackgroundColor', [0.10 0.50 0.30], 'ForegroundColor', 'w', ...
            'Callback', @esportaSempliceExcel);

        uicontrol('Parent', figCentro, 'Style', 'pushbutton', ...
            'String', 'REPORT PDF', ...
            'Position', [350, 95, 290, 40], ...
            'BackgroundColor', [0.75 0.20 0.20], 'ForegroundColor', 'w', ...
            'Callback', @esportaReportPDFAcademic);
    end

    uicontrol('Parent', figCentro, 'Style', 'pushbutton', ...
        'String', 'ESCI', ...
        'Position', [40, 25, 590, 42], ...
        'BackgroundColor', [1 0 0], 'ForegroundColor', 'w', ...
        'Callback', @(~,~) chiudiTutto(figCentro));
end


%  EXPORT EXCEL

function esportaSempliceExcel(~, ~)
    T = readtable('Foglio dati progetto Chiara e Ludo.xlsx', ...
        'Sheet','Epidemiologia','VariableNamingRule','preserve');

    writetable(T,'Report_Epidemiologia.xlsx');
    msgbox('Excel generato con successo');
end

%  PDF REPORT

function esportaReportPDFAcademic(~, ~)

    import mlreportgen.dom.*

    nomeFile = 'Report_Epidemiologico_Autoimmune.pdf';
    doc = Document(nomeFile,'pdf');
    open(doc);

    T = readtable('Foglio dati progetto Chiara e Ludo.xlsx', ...
        'Sheet','Epidemiologia','VariableNamingRule','preserve');

    totCasi = sum(T.Casi_Totali,'omitnan');
    totMorti = sum(T.Casi_Totali .* (T.Tasso_Mortalita/100),'omitnan');
    mortalitaMedia = mean(T.Tasso_Mortalita,'omitnan');

    [grp,names] = findgroups(T.Nome_Malattia);
    somma = splitapply(@sum,T.Casi_Totali,grp);
    [~,idx] = max(somma);
    malTop = string(names(idx));

    %TITOLO
    append(doc, Paragraph('REPORT EPIDEMIOLOGICO DELLE MALATTIE AUTOIMMUNI'));
    append(doc, Paragraph(['Generato il: ' datestr(now,'dd/mm/yyyy HH:MM')]));
    append(doc, HorizontalRule);

    %INTRO
    append(doc, Paragraph("Analisi statistico-epidemiologica del dataset autoimmuni."));

    % KPI
    append(doc, Paragraph(['Casi totali: ', num2str(totCasi)]));
    append(doc, Paragraph(['Morti: ', num2str(round(totMorti))]));
    append(doc, Paragraph(['Mortalità media: ', num2str(mortalitaMedia,'%.2f'), '%']));
    append(doc, Paragraph(['Malattia prevalente: ', char(malTop)]));

    %CONCLUSIONI
    append(doc, Paragraph("Sistema di analisi dati integrato MATLAB + Excel per supporto epidemiologico."));

    close(doc);
    msgbox('Report PDF generato con successo');
end


function chiudiTutto(fig)
    close(fig);
    close all;
end