function scheda_sintomi(idMalattia)
    nomi = {'Sclerosi Multipla', 'Celiachia', 'Diabete Tipo 1', 'Tiroidite di Hashimoto', 'Morbo di Crohn'};
    malattia = nomi{idMalattia};
    
    fig = figure('Name', ['Sintomi - ' malattia], 'NumberTitle', 'off', ...
        'MenuBar', 'none', 'ToolBar', 'none', 'Position', [450, 250, 560, 300], 'Color', 'w');
    
    uicontrol('Parent', fig, 'Style', 'text', 'String', ['⚠️ QUADRO SINTOMATOLOGICO: ' upper(malattia)], ...
        'Position', [20, 245, 520, 30], 'FontSize', 12, 'FontWeight', 'bold', 'BackgroundColor', 'w', ...
        'ForegroundColor', [1.00, 0.35, 0.10], 'HorizontalAlignment', 'left');
    
    % Sistemata la concatenazione di stringhe usando [ , , ] invece di +
    switch malattia
        case 'Sclerosi Multipla'
            t = ['- Stanchezza cronica centrale profonda ed invalidante (fatigue)', newline, ...
                 '- Neurite ottica retrobulbare con dolore e annebbiamento visivo transitorio', newline, ...
                 '- Atassia cerebellare, marcata perdita di equilibrio e vertigini', newline, ...
                 '- Parestesie, alterazioni della sensibilità tattile e spasticità muscolare agli arti.'];
        case 'Celiachia'
            t = ['- Diarrea cronica persistente con quadri gravi di steatorrea', newline, ...
                 '- Dolore addominale ricorrente, crampi e meteorismo intestinale severo', newline, ...
                 '- Sindrome da malassorbimento con conseguente anemia sideropenica refrattaria', newline, ...
                 '- Calo ponderale progressivo, astenia e arresto della crescita staturale nei bambini.'];
        case 'Diabete Tipo 1'
            t = ['- Poliuria marcata dovuta a diuresi osmotica causata dall''iperglicemia', newline, ...
                 '- Polidipsia compensatoria secondaria alla disidratazione dei tessuti', newline, ...
                 '- Polifagia paradossa accompagnata da un calo ponderale repentino ed evidente', newline, ...
                 '- Letargia, visione offuscata e rischio imminente di coma chetoacidotico.'];
        case 'Tiroidite di Hashimoto'
            t = ['- Astenia severa diffusa, sonnolenza diurna e rallentamento psicomotorio', newline, ...
                 '- Intolleranza spiccata al freddo ambientale ed ipotermia basale', newline, ...
                 '- Aumento di peso corporeo ingiustificato a parità di apporto calorico', newline, ...
                 '- Bradicardia, ipercolesterolemia, alopecia, stipsi ostinata e mixedema facciale.'];
        case 'Morbo di Crohn'
            t = ['- Dolore addominale cronico localizzato prevalentemente alla fossa iliaca destra', newline, ...
                 '- Diarrea cronica acquosa o muco-ematica persistente nei mesi', newline, ...
                 '- Febbre serotina, astenia profonda ed inappetenza marcata', newline, ...
                 '- Calo ponderale severo dovuto a malassorbimento e sviluppo di fistole anali dolenti.'];
    end
    
    uicontrol('Parent', fig, 'Style', 'text', 'String', t, 'Position', [20, 20, 520, 210], ...
        'FontSize', 11, 'BackgroundColor', 'w', 'ForegroundColor', 'k', 'HorizontalAlignment', 'left');
end